# Keep this file in sync with docker-compose.yml.

# Build JAVA applications using Apache Maven (http://maven.apache.org)
# For docker image tags see https://hub.docker.com/_/maven/
#
# For general lifecycle information see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

image: dockerhub.ebi.ac.uk/ega/ega-data-api-build-container:latest

# Add the service of docker in docker to allow us to compile the docker images
# https://docs.gitlab.com/runner/executors/kubernetes.html#using-dockerdind
services:
  - name: docker:dind
    alias: dataedge

## List of jobs:
stages:
  - imageBuild

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  TRAVIS_BUILD_DIR: $CI_PROJECT_DIR

imageBuild:
  stage: imageBuild
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG  
  before_script:
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_TAG  
  script:
    - mvn clean install "-DdockerRegistry=$CI_REGISTRY_IMAGE" "-Dimage.version=testing-notuse" -P production -DskipTests
