# Keep this file in sync with docker-compose.yml.

# Build JAVA applications using Apache Maven (http://maven.apache.org)
# For docker image tags see https://hub.docker.com/_/maven/
#
# For general lifecycle information see https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html

image: maven:3.6.3-openjdk-8-slim

# Add the service of docker in docker to allow us to compile the docker images and include the environment variables as specified
# https://docs.gitlab.com/runner/executors/kubernetes.html#using-dockerdind
services:
  - docker:dind
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

## List of jobs:
stages:
  #- unitTest
  - integrationTest
  - imageBuild

# Cache downloaded dependencies and plugins between builds.
# To keep cache across branches add 'key: "$CI_JOB_NAME"'
cache:
  paths:
    - .m2/repository

## Diffent stages for the CICD of Data API
#unitTest:
#  stage: unitTest
  #before_script:
  #  - mvn dependency:purge-local-repository install -DskipTests=true -P production -Dmaven.javadoc.skip=true -B -V -DskipDockerPush
#  script: mvn test

integrationTest:
  stage: integrationTest
  before_script:
    - docker info
    - mvn dependency:purge-local-repository install -DskipTests=true -P production -Dmaven.javadoc.skip=true -B -V -DskipDockerPush
    - sudo service postgresql stop
    - sudo mkdir -p /usr/local/share/ca-certificates/ca/
    - sudo cp extras/certificate/rootCA.pem /usr/local/share/ca-certificates/ca/CA.crt
    - sudo chmod 644 /usr/local/share/ca-certificates/ca/CA.crt
    - sudo update-ca-certificates
    - docker build -t ega-data-api/ega-dataedge  --file Dockerfile.dataedge .
    - docker build -t ega-data-api/ega-res  --file Dockerfile.res .
    - docker build -t ega-data-api/ega-keyserver  --file Dockerfile.keyserver .
    - docker build -t ega-data-api/ega-filedatabase  --file Dockerfile.filedatabase .
    - docker build -t ega-data-api/ega-postgres --file extras/postgresdb/Dockerfile .
    - cd extras && source ./variables.sh
    - docker-compose up -d
    - sleep 90
    - cd ../ega-data-api-it
  script:
    - mvn test

imageBuild:
  stage: imageBuild
  only:
    - master
  before_script:
    - mvn dependency:purge-local-repository install -DskipTests=true -P production -Dmaven.javadoc.skip=true -B -V -DskipDockerPush
  script: ./extras/travis_push_docker_hub.sh
