language: java

services: docker

jdk: oraclejdk8
install:
  # installing dependencies and skipping docker push
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DskipDockerPush

cache:
  directories:
  - $HOME/.m2

  
stages:
  - name: unit test
    if: type IN (push, pull_request)
  - name: integ test
    if: type IN (pull_request)
  - name: image build
    if: type IN (push)    
    
jobs:
  include:
    - stage: unit test
      script: mvn test
    - stage: integ test
      before_script:
        - sudo service postgresql stop
        - cd extras
        - docker-compose up -d
        - sleep 90
        - cd ../ega-data-api-it
      script:
        - mvn test -Dtest=!DataedgeIntgTest,!MetadataControllerIntgTest
    - stage: image build
      script: ./extras/travis_push_docker_hub.sh

notifications:
  email: false      