language: java

services: docker

jdk: oraclejdk8
install:
  # installing dependencies and skipping docker push
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DskipDockerPush

cache:
  directories:
  - $HOME/.m2

  
stages:
  - name: unittests
    if: type IN (push, pull_request)
  - name: integtests
    if: type IN (pull_request)
    
jobs:
  include:
    - stage: unittests
      script: mvn test
    - stage: integtests
      before_script:
        - sudo service postgresql stop
        - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
        - cd extras
        - docker-compose up -d
        - sleep 150
        - cd ../ega-data-api-it
      script:
        - mvn test
        