language: java

services: docker

jdk: oraclejdk8

dist: trusty

install:
  # installing dependencies and skipping docker push
  - mvn dependency:purge-local-repository install -DskipTests=true -P production -Dmaven.javadoc.skip=true -B -V -DskipDockerPush

cache:
  directories:
  - $HOME/.m2

  
stages:
  - name: unit test
    if: type IN (push, pull_request)
  - name: integ test
    if: type IN (push, pull_request)
  - name: image build
    if: type = push AND branch = master       
    
jobs:
  include:
    - stage: unit test
      script: mvn test
    - stage: integ test
      before_script:
        - sudo service postgresql stop   
        - sudo mkdir -p /usr/local/share/ca-certificates/ca/        
        - sudo cp extras/certificate/rootCA.pem /usr/local/share/ca-certificates/ca/CA.crt
        - sudo chmod 644 /usr/local/share/ca-certificates/ca/CA.crt
        - sudo update-ca-certificates
        - docker build -t ega-data-api/ega-dataedge  --file Dockerfile.dataedge .
        - docker build -t ega-data-api/ega-res  --file Dockerfile.res .
        - docker build -t ega-data-api/ega-keyserver  --file Dockerfile.keyserver .
        - docker build -t ega-data-api/ega-filedatabase  --file Dockerfile.filedatabase .        
        - docker build -t ega-data-api/ega-postgres --file extras/postgresdb/Dockerfile .
        - cd extras && source ./variables.sh
        - docker-compose up -d
        - sleep 90
        - cd ../ega-data-api-it
      script:
        - mvn test
    - stage: image build
      script: ./extras/travis_push_docker_hub.sh

notifications:
  email: false      