language: java

services: docker

jdk: oraclejdk8
install:
  # installing dependencies and skipping docker push
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DskipDockerPush

cache:
  directories:
  - $HOME/.m2

script:
  ## Travis run on master branch and not a PR
  - if [[ "$TRAVIS_BRANCH" == "master" && $TRAVIS_PULL_REQUEST == "false" ]]; then
      # this is after a PR has been approved
      ./extras/travis_push_docker_hub.sh
    else
      mvn clean install -DskipDockerPush ;
    fi
