spring.profiles: no-oss

eureka.client.enabled: false

hystrix.command.default.execution.timeout.enabled: false

management.server.port: -1
management.endpoints.jmx.exposure.include: "*"
endpoints.enabled: false
endpoints.health.enabled: true
endpoints.info.enabled: true
endpoints.refresh.enabled: false