spring.profiles: no-oss

eureka.client.enabled: false

security.oauth2.resource.jwt.key-value: ${JWTKEY}

FILEDATABASE:
  listOfServers: ${FILEDATABASE_SERVERS:filedatabase}

RES2:
  listOfServers: ${RES_SERVERS:res}

KEYSERVER:
  listOfServers: ${KEYS_SERVERS:keys}
