spring.profiles: no-oss

eureka.client.enabled: false

# Used when a custom token is generated and we have an ASCII encoded key
security.oauth2.resource.jwt.key-value: ${JWTKEY}

# Format should be: jdbc:postgresql://<ip_or_service>:<port>/<db_name>
spring.datasource.url: ${DB_URL}

FILEDATABASE:
  listOfServers: ${FILEDATABASE_SERVERS:filedatabase}

RES2:
  listOfServers: ${RES_SERVERS:res}

KEYSERVER:
  listOfServers: ${KEYS_SERVERS:keys}
