spring.profiles: no-oss,LocalEGA,log-transfer,repo-logger,db-repo-logger

eureka.client.enabled: false

management.server.port: -1
management.endpoints.jmx.exposure.include: "*"
endpoints.enabled: false
endpoints.health.enabled: true
endpoints.info.enabled: true
endpoints.refresh.enabled: false

FILEDATABASE:
  listOfServers: ${FILEDATABASE_SERVERS:filedatabase}

RES2:
  listOfServers: ${RES_SERVERS:res}

KEYSERVER:
  listOfServers: ${KEYS_SERVERS:keys}


ega.ebi.fire.url:
ega.ebi.fire.archive:
ega.ebi.fire.key:
ega.sharedpass.path: /src/test/resources/testing
service.archive.class: