spring.profiles: no-oss

eureka.client.enabled: false

spring.jpa.properties.hibernate.default_schema: ${DB_SCHEMA:local_ega}

spring.datasource.driverClassName: org.postgresql.Driver
spring.jpa.hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy

spring.jpa.show-sql: true

spring.datasource.url: ${DB_URL} #jdbc:postgresql://localega-db:port/lega

spring.datasource.username: ${DB_USERNAME}

spring.datasource.password: ${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto: validate

hystrix.command.default.execution.timeout.enabled: false
