spring.profiles: no-oss

eureka.client.enabled: false

# By default when integrating with LocaEGA we will use schema `local_ega`
spring.jpa.properties.hibernate.default_schema: ${DB_SCHEMA:local_ega}

spring.datasource.driverClassName: org.postgresql.Driver

#spring.jpa.show-sql: true

# Format should be: jdbc:postgresql://<ip_or_service>:<port>/<db_name>
spring.datasource.url: ${DB_URL}

spring.datasource.username: ${DB_USERNAME}

spring.datasource.password: ${DB_PASSWORD}


hystrix.command.default.execution.timeout.enabled: false
