swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:9090'
basePath: /
tags:
  - name: file-controller
    description: File Controller
  - name: stats-controller
    description: Stats Controller
paths:
  /file:
    get:
      tags:
        - file-controller
      summary: getFile
      operationId: getFileUsingGET
      produces:
        - 'octet-stream'
      parameters:
        - name: destinationFormat
          in: query
          description: destinationFormat
          required: false
          type: string
          default: plain
        - name: destinationIV
          in: query
          description: destinationIV
          required: false
          type: string
        - name: destinationKey
          in: query
          description: destinationKey
          required: false
          type: string
        - name: endCoordinate
          in: query
          description: endCoordinate
          required: false
          type: integer
          default: 0
          format: int64
        - name: filePath
          in: query
          description: filePath
          required: true
          type: string
        - name: fileSize
          in: query
          description: fileSize
          required: false
          type: integer
          default: 0
          format: int64
        - name: httpAuth
          in: query
          description: httpAuth
          required: false
          type: string
        - name: id
          in: query
          description: id
          required: false
          type: string
        - name: sourceFormat
          in: query
          description: sourceFormat
          required: false
          type: string
          default: plain
        - name: sourceIV
          in: query
          description: sourceIV
          required: false
          type: string
        - name: sourceKey
          in: query
          description: sourceKey
          required: false
          type: string
        - name: startCoordinate
          in: query
          description: startCoordinate
          required: false
          type: integer
          default: 0
          format: int64
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/file/archive/{id}':
    get:
      tags:
        - file-controller
      summary: getArchiveFile
      operationId: getArchiveFileUsingGET
      produces:
        - 'octet-stream'
      parameters:
        - name: destinationFormat
          in: query
          description: destinationFormat
          required: true
          type: string
        - name: destinationIV
          in: query
          description: destinationIV
          required: false
          type: string
        - name: destinationKey
          in: query
          description: destinationKey
          required: false
          type: string
        - name: endCoordinate
          in: query
          description: endCoordinate
          required: false
          type: integer
          default: 0
          format: int64
        - name: id
          in: path
          description: id
          required: true
          type: string
        - name: startCoordinate
          in: query
          description: startCoordinate
          required: false
          type: integer
          default: 0
          format: int64
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/file/archive/{id}/size':
    get:
      tags:
        - file-controller
      summary: getArchiveFileSize
      operationId: getArchiveFileSizeUsingGET
      produces:
        - 'long'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: integer
            format: int64
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/file/test1/{size}':
    get:
      tags:
        - file-controller
      summary: getArchiveFile
      operationId: getArchiveFileUsingGET_1
      produces:
        - '*/*'
      parameters:
        - name: size
          in: path
          description: size
          required: true
          type: string
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/file/test2/{size}':
    get:
      tags:
        - file-controller
      summary: doDownload
      operationId: doDownloadUsingGET
      produces:
        - '*/*'
      parameters:
        - name: random
          in: query
          description: random
          required: false
          type: boolean
        - name: size
          in: path
          description: size
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /stats/load:
    get:
      tags:
        - stats-controller
      summary: get
      operationId: getUsingGET
      produces:
        - 'long'
      responses:
        '200':
          description: OK
          schema:
            type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  ModelAndView:
    type: object
    properties:
      empty:
        type: boolean
      model:
        type: object
      modelMap:
        type: object
        additionalProperties:
          type: object
      reference:
        type: boolean
      status:
        type: string
        enum:
          - '100'
          - '101'
          - '102'
          - '103'
          - '200'
          - '201'
          - '202'
          - '203'
          - '204'
          - '205'
          - '206'
          - '207'
          - '208'
          - '226'
          - '300'
          - '301'
          - '302'
          - '303'
          - '304'
          - '305'
          - '307'
          - '308'
          - '400'
          - '401'
          - '402'
          - '403'
          - '404'
          - '405'
          - '406'
          - '407'
          - '408'
          - '409'
          - '410'
          - '411'
          - '412'
          - '413'
          - '414'
          - '415'
          - '416'
          - '417'
          - '418'
          - '419'
          - '420'
          - '421'
          - '422'
          - '423'
          - '424'
          - '426'
          - '428'
          - '429'
          - '431'
          - '451'
          - '500'
          - '501'
          - '502'
          - '503'
          - '504'
          - '505'
          - '506'
          - '507'
          - '508'
          - '509'
          - '510'
          - '511'
      view:
        $ref: '#/definitions/View'
      viewName:
        type: string
    title: ModelAndView
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - '100'
          - '101'
          - '102'
          - '103'
          - '200'
          - '201'
          - '202'
          - '203'
          - '204'
          - '205'
          - '206'
          - '207'
          - '208'
          - '226'
          - '300'
          - '301'
          - '302'
          - '303'
          - '304'
          - '305'
          - '307'
          - '308'
          - '400'
          - '401'
          - '402'
          - '403'
          - '404'
          - '405'
          - '406'
          - '407'
          - '408'
          - '409'
          - '410'
          - '411'
          - '412'
          - '413'
          - '414'
          - '415'
          - '416'
          - '417'
          - '418'
          - '419'
          - '420'
          - '421'
          - '422'
          - '423'
          - '424'
          - '426'
          - '428'
          - '429'
          - '431'
          - '451'
          - '500'
          - '501'
          - '502'
          - '503'
          - '504'
          - '505'
          - '506'
          - '507'
          - '508'
          - '509'
          - '510'
          - '511'
      statusCodeValue:
        type: integer
        format: int32
    title: ResponseEntity
  View:
    type: object
    properties:
      contentType:
        type: string
    title: View
