swagger: '2.0'
info:
  description: Api Documentation
  version: '1.0'
  title: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'localhost:9090'
basePath: /
tags:
  - name: file-controller
    description: File Controller
  - name: stats-controller
    description: Stats Controller
paths:
  /file:
    get:
      tags:
        - file-controller
      summary: getFile
      operationId: getFileUsingGET
      produces:
        - 'octet-stream'
      parameters:
        - name: destinationFormat
          in: query
          description: destinationFormat
          required: false
          type: string
          default: plain
        - name: destinationIV
          in: query
          description: destinationIV
          required: false
          type: string
        - name: destinationKey
          in: query
          description: destinationKey
          required: false
          type: string
        - name: endCoordinate
          in: query
          description: endCoordinate
          required: false
          type: integer
          default: 0
          format: int64
        - name: filePath
          in: query
          description: filePath
          required: true
          type: string
        - name: fileSize
          in: query
          description: fileSize
          required: false
          type: integer
          default: 0
          format: int64
        - name: httpAuth
          in: query
          description: httpAuth
          required: false
          type: string
        - name: id
          in: query
          description: id
          required: false
          type: string
        - name: sourceFormat
          in: query
          description: sourceFormat
          required: false
          type: string
          default: plain
        - name: sourceIV
          in: query
          description: sourceIV
          required: false
          type: string
        - name: sourceKey
          in: query
          description: sourceKey
          required: false
          type: string
        - name: startCoordinate
          in: query
          description: startCoordinate
          required: false
          type: integer
          default: 0
          format: int64
      responses:
        '200':
          description: OK
          examples:
            octet-stream:
              'c1c14c03471b51597e80f09d010ffe3df50a3f0466966a63c130000b6cb2f4bf08e49e92fe05ae17bdce5b8c6e41f9fedd9930f103576489b253997493a9c305e894f380ae3632616ad56e201a48096cef3ee6c835e882b10ea45fd420fa8561d9fb5e73654f5722485070b7faeea76381b2dc2dd380f9aae4919195d23970e2af9af8456981d654de78012966cffb3219d81646446111126a1818f777e0498783854f90776a65878aac00c1c18da442aecf4e25caaf8badb918b449984d98b645e23f0a17c9ad796ad990d53b5f84a97ce01ed0b164c1f670ce6cb176875189264fcad6d339de9a48f538eb959e8091d2e62a94709c93e00c83942345c04250a9cc855f078bcd664e0744d57c1ef540e68a348b71033f7506267ac68f7dbe9d41641e895bae31977119de55a71c1f208092df9c20294b263aec176b188aa5ade7f89967898bb353323ec422b7f12e39aa30d636babad7c5777adccbaab69cb6ead334a6b60b04e01c057278f2a5551149210989ea9329e2b185c586300f1abd3c3c0a2cff9780ecaec5f16010b796665f2f07922991d42bd18956dd475af6c709bb45f0a211e319473699ce6e6eb2dc00e6514a39889845a2c944e3885a71123e9f51c7f26273e7013ca5305681312db86f73cd1e4c7791d3c6af8a80b11245ce1cf4e3d4dc1fd5a68f129c6c8c71d3e05b87ce71dfa8d879282d0eaa63658924df67a6a740634ea7290ddf8cbb12d27a011d4951e2154c56ca72e4bd63f68ffcf8a2b831b2805fa1dd90a4eb71aecdc94e45aa11b632f539748eb9d866a917034ffac6f1517a4202aa91d235bf34eb9a52e73bfc2829b6c37ba9de3814c0f074a15d424d0bbe0e3540306cb781346c54b687fc9d0c136ca700a07ac6abaec1f1a37f773b04d7891ab5c7'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/file/archive/{id}':
    get:
      tags:
        - file-controller
      summary: getArchiveFile
      operationId: getArchiveFileUsingGET
      produces:
        - 'octet-stream'
      parameters:
        - name: destinationFormat
          in: query
          description: destinationFormat
          required: true
          type: string
        - name: destinationIV
          in: query
          description: destinationIV
          required: false
          type: string
        - name: destinationKey
          in: query
          description: destinationKey
          required: false
          type: string
        - name: endCoordinate
          in: query
          description: endCoordinate
          required: false
          type: integer
          default: 0
          format: int64
        - name: id
          in: path
          description: id
          required: true
          type: string
        - name: startCoordinate
          in: query
          description: startCoordinate
          required: false
          type: integer
          default: 0
          format: int64
      responses:
        '200':
          description: OK
          examples:
            octet-stream:
              'c1c14c03471b51597e80f09d010ffe3df50a3f0466966a63c130000b6cb2f4bf08e49e92fe05ae17bdce5b8c6e41f9fedd9930f103576489b253997493a9c305e894f380ae3632616ad56e201a48096cef3ee6c835e882b10ea45fd420fa8561d9fb5e73654f5722485070b7faeea76381b2dc2dd380f9aae4919195d23970e2af9af8456981d654de78012966cffb3219d81646446111126a1818f777e0498783854f90776a65878aac00c1c18da442aecf4e25caaf8badb918b449984d98b645e23f0a17c9ad796ad990d53b5f84a97ce01ed0b164c1f670ce6cb176875189264fcad6d339de9a48f538eb959e8091d2e62a94709c93e00c83942345c04250a9cc855f078bcd664e0744d57c1ef540e68a348b71033f7506267ac68f7dbe9d41641e895bae31977119de55a71c1f208092df9c20294b263aec176b188aa5ade7f89967898bb353323ec422b7f12e39aa30d636babad7c5777adccbaab69cb6ead334a6b60b04e01c057278f2a5551149210989ea9329e2b185c586300f1abd3c3c0a2cff9780ecaec5f16010b796665f2f07922991d42bd18956dd475af6c709bb45f0a211e319473699ce6e6eb2dc00e6514a39889845a2c944e3885a71123e9f51c7f26273e7013ca5305681312db86f73cd1e4c7791d3c6af8a80b11245ce1cf4e3d4dc1fd5a68f129c6c8c71d3e05b87ce71dfa8d879282d0eaa63658924df67a6a740634ea7290ddf8cbb12d27a011d4951e2154c56ca72e4bd63f68ffcf8a2b831b2805fa1dd90a4eb71aecdc94e45aa11b632f539748eb9d866a917034ffac6f1517a4202aa91d235bf34eb9a52e73bfc2829b6c37ba9de3814c0f074a15d424d0bbe0e3540306cb781346c54b687fc9d0c136ca700a07ac6abaec1f1a37f773b04d7891ab5c7'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/file/archive/{id}/size':
    get:
      tags:
        - file-controller
      summary: getArchiveFileSize
      operationId: getArchiveFileSizeUsingGET
      produces:
        - 'long'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: integer
            format: int64
          examples:
            long:
              719
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/file/test1/{size}':
    get:
      tags:
        - file-controller
      summary: getArchiveFile
      operationId: getArchiveFileUsingGET_1
      produces:
        - '*/*'
      parameters:
        - name: size
          in: path
          description: size
          required: true
          type: string
      responses:
        '200':
          description: OK
          examples:
            long:
              551
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/file/test2/{size}':
    get:
      tags:
        - file-controller
      summary: doDownload
      operationId: doDownloadUsingGET
      produces:
        - '*/*'
      parameters:
        - name: random
          in: query
          description: random
          required: false
          type: boolean
        - name: size
          in: path
          description: size
          required: true
          type: string
      responses:
        '200':
          description: OK
          schema:
            type: string
          examples:
            long:
              184
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /stats/load:
    get:
      tags:
        - stats-controller
      summary: get
      operationId: getUsingGET
      produces:
        - 'long'
      responses:
        '200':
          description: OK
          schema:
            type: string
          examples:
            long:
              1029
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  ModelAndView:
    type: object
    properties:
      empty:
        type: boolean
      model:
        type: object
      modelMap:
        type: object
        additionalProperties:
          type: object
      reference:
        type: boolean
      status:
        type: string
        enum:
          - '100'
          - '101'
          - '102'
          - '103'
          - '200'
          - '201'
          - '202'
          - '203'
          - '204'
          - '205'
          - '206'
          - '207'
          - '208'
          - '226'
          - '300'
          - '301'
          - '302'
          - '303'
          - '304'
          - '305'
          - '307'
          - '308'
          - '400'
          - '401'
          - '402'
          - '403'
          - '404'
          - '405'
          - '406'
          - '407'
          - '408'
          - '409'
          - '410'
          - '411'
          - '412'
          - '413'
          - '414'
          - '415'
          - '416'
          - '417'
          - '418'
          - '419'
          - '420'
          - '421'
          - '422'
          - '423'
          - '424'
          - '426'
          - '428'
          - '429'
          - '431'
          - '451'
          - '500'
          - '501'
          - '502'
          - '503'
          - '504'
          - '505'
          - '506'
          - '507'
          - '508'
          - '509'
          - '510'
          - '511'
      view:
        $ref: '#/definitions/View'
      viewName:
        type: string
    title: ModelAndView
  ResponseEntity:
    type: object
    properties:
      body:
        type: object
      statusCode:
        type: string
        enum:
          - '100'
          - '101'
          - '102'
          - '103'
          - '200'
          - '201'
          - '202'
          - '203'
          - '204'
          - '205'
          - '206'
          - '207'
          - '208'
          - '226'
          - '300'
          - '301'
          - '302'
          - '303'
          - '304'
          - '305'
          - '307'
          - '308'
          - '400'
          - '401'
          - '402'
          - '403'
          - '404'
          - '405'
          - '406'
          - '407'
          - '408'
          - '409'
          - '410'
          - '411'
          - '412'
          - '413'
          - '414'
          - '415'
          - '416'
          - '417'
          - '418'
          - '419'
          - '420'
          - '421'
          - '422'
          - '423'
          - '424'
          - '426'
          - '428'
          - '429'
          - '431'
          - '451'
          - '500'
          - '501'
          - '502'
          - '503'
          - '504'
          - '505'
          - '506'
          - '507'
          - '508'
          - '509'
          - '510'
          - '511'
      statusCodeValue:
        type: integer
        format: int32
    title: ResponseEntity
  View:
    type: object
    properties:
      contentType:
        type: string
    title: View
