# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  one: 1
  two: 2
  three: 3
  four: 4
  five: 5 

image:
  metadata: 
      eureka: eureka-app
      key: key-app
      filedatabase: filedatabase-app
      res: res-app
  tag: stable
  pullPolicy: Always
  imageSecrets: regcredc 
  repository: 
      eureka:
        value: anandmohan777/eureka
        tagMajor: 1
        tagMinor: 0
        port: 8761
        nodeport: 30761
        debug: 5060
        debugNodePort: 30060       
      key:
        value: anandmohan777/key
        tagMajor: 1
        tagMinor: 0
        port: 9095
        nodeport: 30095
        debug: 5094
        debugNodePort: 30094      
      filedatabase:
        value: anandmohan777/filedatabase
        tagMajor: 1
        tagMinor: 0
        port: 9050
        nodeport: 30050
        debug: 5049
        debugNodePort: 30049   
      res:
        value: anandmohan777/res
        tagMajor: 1
        tagMinor: 0
        port: 9090
        nodeport: 30090
        debug: 5089
        debugNodePort: 30089  
      dataedge:
        value: anandmohan777/dataedge
        tagMajor: 1
        tagMinor: 0
        port: 9059
        nodeport: 30059
        debug: 5058
        debugNodePort: 30058         

configService: "http://config.default.svc.cluster.local"
  
group:
  one: group1
  two: group2
  three: group3
  four: group4
  five: group5
  six: group6
  seven: group7
  eight: group8  

logdirectory:
  path: /tmp/logs