# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  metadata: 
      eureka: eureka-app
      key: key-app
      filedatabase: filedatabase-app
      res: res-app
  tag: stable
  pullPolicy: Always
  repository: 
      eureka:
        value: 192.168.0.37/eureka
        tag: v1
        port: 8761
        nodeport: 30761
      key:
        value: 192.168.0.37/key
        tag: v1  
        port: 9095
        nodeport: 30095
      filedatabase:
        value: 192.168.0.37/filedatabase
        tag: v1
        port: 9050
        nodeport: 30050
      res:
        value: 192.168.0.37/res
        tag: v1
        port: 9090
        nodeport: 30090

configService: "http://config.default.svc.cluster.local"
  
group:
  one: group1
  two: group2
