# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  metadata: 
      eureka: eureka-app
      key: key-app
      filedatabase: filedatabase-app
      res: res-app
  tag: stable
  pullPolicy: Always
  repository: 
      eureka:
        value: anandmohan777/eureka
        tag: v2
        port: 8761
        nodeport: 30761
        debug: 5060
        debugNodePort: 30060       
      key:
        value: anandmohan777/key
        tag: v2  
        port: 9095
        nodeport: 30095
        debug: 5094
        debugNodePort: 30094      
      filedatabase:
        value: anandmohan777/filedatabase
        tag: v2
        port: 9050
        nodeport: 30050
        debug: 5049
        debugNodePort: 30049   
      res:
        value: anandmohan777/res
        tag: v2
        port: 9090
        nodeport: 30090
        debug: 5089
        debugNodePort: 30089    

configService: "http://config.default.svc.cluster.local"
  
group:
  one: group1
  two: group2
