---
apiVersion: v1
kind: Service
metadata:
    name: config
    labels:
        app: {{ .Values.image.metadata.config }}
spec:
    ports:
    -   port: {{ .Values.image.repository.config.port }}
        protocol: TCP
    selector:
        app: {{ .Values.image.metadata.config }}
