# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  metadata: 
      config: config-app
      postgres: postgres-app
  tag: stable
  pullPolicy: Always
  repository: 
      config:
        value: anandmohan777/config
        tag: v2
        port: 8888
      postgres:
        value: anandmohan777/postgres
        tag: v2
        port: 5432
        nodePort: 30432
  
group:
  one: group1
  two: group2
