# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount:
  one: 1
  two: 2
  three: 3
  four: 4
  five: 5

image:
  metadata: 
      config: config-app
      postgres: postgres-app
  tag: stable
  pullPolicy: Always
  repository: 
      config:
        value: anandmohan777/config
        tagMajor: 1
        tagMinor: 0
        port: 8888
      postgres:
        value: anandmohan777/postgres
        tag: v2
        port: 5432
        nodePort: 30432
  
group:
  one: group1
  two: group2
  three: group3
  four: group4
  five: group5
  six: group6
  seven: group7
  eight: group8  

logdirectory:
  path: /tmp/logs
