# Default values for demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  metadata: 
      config: config-app
  tag: stable
  pullPolicy: Always
  repository: 
      config:
        value: 192.168.0.37/config
        tag: v1
        port: 8888
  
group:
  one: group1
  two: group2
