version: "3.4"
services:
  dataedge:
    image: ega-data-api/ega-dataedge
    ports:
      - "9058:9058"
      - "5059:5059"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss
      - server.port=9058
      - JWTKEY=${JWTKEY}
      - FILEDATABASE.listOfServers=filedatabase:9051
      - RES2.listOfServers=resserver:9092
      - KEYSERVER.listOfServers=keyserver:9095
      - ega.ega.external.url=https://ega.ebi.ac.uk:8051/elixir/data/files/
      - ega.ega.cram.fasta=/homes/ega-prod/ngs_dev/Homo_sapiens_assembly38.fasta
      - ega.ega.cram.fasta.a=/homes/ega-prod/ngs_dev/Homo_sapiens_assembly38.fasta 
      - ega.ega.cram.fasta.b=/homes/ega-prod/ngs_dev/hsapiens.GRCh37.fasta
    networks:
      - webnet
      
  resserver:
    image: ega-data-api/ega-res
    ports:
      - "9092:9092"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss,LocalEGA
      - server.port=9092
      - ega.ebi.aws.access.key=${MINIO_ACCESS_KEY}
      - ega.ebi.aws.access.secret=${MINIO_SECRET_KEY}
      - ega.ebi.aws.endpoint.url=http://archive:9000
      - ega.ebi.aws.endpoint.region=${MINIO_REGION}
      - ega.sharedpass.path=/src/test/resources/pgp/ega.shared.pass
      - FILEDATABASE.listOfServers=filedatabase:9051
      - RES2.listOfServers=resserver:9092
      - KEYSERVER.listOfServers=keyserver:9095 
      - EGA_EGA_CRAM_FASTA_A=""
      - EGA_EGA_CRAM_FASTA_B=""
      - EGA_EBI_FIRE_URL=""
      - EGA_EBI_FIRE_ARCHIVE=""
      - EGA_EBI_FIRE_KEY=""
      - service.archive.class=""
    networks:
      - webnet  

  keyserver:
    image: ega-data-api/ega-keyserver
    ports:
      - "9095:9095"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss
      - server.port=9095        
      - ega.key.path=/src/test/resources/pgp/ega.sec
      - ega.keypass.path=/src/test/resources/pgp/ega.sec.pass
      - ega.sharedpass.path=/src/test/resources/pgp/ega.shared.pass
      - ega.publickey.url=/src/test/resources/pgp/ega.pub
      - ega.legacy.path=/src/test/resources/pgp/legacy.pass     
    networks:
      - webnet       
      
  filedatabase:
    image: ega-data-api/ega-filedatabase
    depends_on: 
      - postgres
    ports:
      - "9051:9051"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss
      - server.port=9051
      - DB_SCHEMA=${POSTGRES_SCHEMA}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    networks:
      - webnet        
      
  postgres:
    image: ega-data-api/ega-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - webnet

  archive:
    image: minio/minio
    entrypoint: sh
    command: -c '/usr/bin/minio server /data'
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY} 
    networks:
      - webnet

  createbucketminio:
    image: minio/mc
    depends_on:
      - archive
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://archive:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb myminio/lega;
      /usr/bin/mc cp /14.enc myminio/lega;
      exit 0;"
    volumes:
      - "./14.enc:/14.enc"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}       
    networks:
      - webnet
      
networks:
  webnet:
