version: "3.4"
services:
  dataedge:
    image: ega-data-api/ega-dataedge
    ports:
      - "9058:9058"
      - "5059:5059"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss,LocalEGA,integration-test
      - server.port=9058
      - JWTKEY=${JWTKEY}
      - FILEDATABASE.listOfServers=filedatabase:9051
      - RES2.listOfServers=resserver:9092
      - KEYSERVER.listOfServers=keyserver:9095
      - PERMISSIONSDATABASESERVER.listOfServers=dataserver:9054
      - ega.ega.external.url=https://ega.ebi.ac.uk:8051/elixir/data/files/
      - ega.ega.cram.fasta=/homes/ega-prod/ngs_dev/Homo_sapiens_assembly38.fasta
      - ega.ega.cram.fasta.a=/homes/ega-prod/ngs_dev/Homo_sapiens_assembly38.fasta 
      - ega.ega.cram.fasta.b=/homes/ega-prod/ngs_dev/hsapiens.GRCh37.fasta
      - ega.internal.filedatabase.url=https://FILEDATABASE
      - ega.internal.res.url=https://RES2
      - ega.internal.key.url=https://KEYSERVER
      - ega.aai.proxy.url=https://ega.ebi.ac.uk:8053/ega-openid-connect-server
      - ega.aai.proxy.basic-authorization=test-auth
      - ega.internal.data.url=http://PERMISSIONSDATABASE
    volumes:
      - "$TRAVIS_BUILD_DIR/extras/certificate/rootCA.pem:/etc/ssl/certs/ca-certificates.crt"   
      - "$TRAVIS_BUILD_DIR/extras/certificate/server.p12:/dataedge.p12"               
    networks:
      - webnet

  resserver:
    image: ega-data-api/ega-res
    ports:
      - "9092:9092"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss,LocalEGA,log-transfer,repo-logger,db-repo-logger
      - server.port=9092
      - ega.ebi.aws.access.key=${MINIO_ACCESS_KEY}
      - ega.ebi.aws.access.secret=${MINIO_SECRET_KEY}
      - ega.ebi.aws.endpoint.url=http://archiveminio:9000
      - ega.ebi.aws.endpoint.region=${MINIO_REGION}
      - ega.sharedpass.path=/pgp/ega.shared.pass
      - FILEDATABASE.listOfServers=filedatabase:9051
      - RES2.listOfServers=resserver:9092
      - KEYSERVER.listOfServers=keyserver:9095
      - DB_SCHEMA=${POSTGRES_SCHEMA_DOWNLOAD}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_URL=jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}      
      - EGA_EGA_CRAM_FASTA_A=""
      - EGA_EGA_CRAM_FASTA_B=""
      - EGA_EBI_FIRE_URL=""
      - EGA_EBI_FIRE_ARCHIVE=""
      - EGA_EBI_FIRE_KEY=""
      - service.archive.class=""
      - ega.internal.filedatabase.url=https://FILEDATABASE
      - ega.internal.res.url=https://RES2
      - ega.internal.key.url=https://KEYSERVER      
    volumes:
      - "$TRAVIS_BUILD_DIR/extras/certificate/rootCA.pem:/etc/ssl/certs/ca-certificates.crt"   
      - "$TRAVIS_BUILD_DIR/extras/certificate/server.p12:/resserver.p12"    
      - "$TRAVIS_BUILD_DIR/ega-data-api-res/src/test/resources/pgp:/pgp"                        
    networks:
      - webnet

  keyserver:
    image: ega-data-api/ega-keyserver
    ports:
      - "9095:9095"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss
      - server.port=9095        
      - ega.key.path=/pgp/ega.sec
      - ega.keypass.path=/pgp/ega.sec.pass
      - ega.sharedpass.path=/pgp/ega.shared.pass
      - ega.publickey.url=/pgp/ega.pub
      - ega.legacy.path=/pgp/legacy.pass
    volumes:
      - "$TRAVIS_BUILD_DIR/extras/certificate/rootCA.pem:/etc/ssl/certs/ca-certificates.crt"   
      - "$TRAVIS_BUILD_DIR/extras/certificate/server.p12:/keyserver.p12"
      - "$TRAVIS_BUILD_DIR/ega-data-api-key/src/test/resources/pgp:/pgp"
    networks:
      - webnet

  postgresdb:
    image: ega-data-api/ega-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - webnet

  filedatabase:
    image: ega-data-api/ega-filedatabase
    depends_on: 
      - postgresdb
    ports:
      - "9051:9051"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss
      - server.port=9051
      - DB_SCHEMA=${POSTGRES_SCHEMA}
      - DB_USERNAME=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_URL=jdbc:postgresql://postgresdb:5432/${POSTGRES_DB}
    volumes:
      - "$TRAVIS_BUILD_DIR/extras/certificate/rootCA.pem:/etc/ssl/certs/ca-certificates.crt"   
      - "$TRAVIS_BUILD_DIR/extras/certificate/server.p12:/filedatabase.p12"      
    networks:
      - webnet

  archiveminio:
    image: minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /data/lega && /usr/bin/minio server /data'
    ports:
      - "9000:9000"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY} 
    networks:
      - webnet

  createbucketminio:
    image: minio/mc
    depends_on: 
      - archiveminio
    entrypoint: >
      /bin/sh -c "sleep 25;
      /usr/bin/mc config host add myminio http://archiveminio:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc cp /14.enc myminio/lega;
      exit 0;"
    volumes:
      - "./14.enc:/14.enc"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}     
    networks:
      - webnet

networks:
  webnet:
