version: "3.4"
services:
  dataedge:
    image: ega-data-api/ega-dataedge
    ports:
      - "9058:9058"
      - "5059:5059"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss
      - server.port=9058
      - JWTKEY=${JWTKEY}
      - FILEDATABASE.listOfServers=filedatabase:9051
      - RES2.listOfServers=resserver:9092
      - KEYSERVER.listOfServers=keyserver:9095
      - ega.ega.external.url=https://ega.ebi.ac.uk:8051/elixir/data/files/
      - ega.ega.cram.fasta=/homes/ega-prod/ngs_dev/Homo_sapiens_assembly38.fasta
      - ega.ega.cram.fasta.a=/homes/ega-prod/ngs_dev/Homo_sapiens_assembly38.fasta 
      - ega.ega.cram.fasta.b=/homes/ega-prod/ngs_dev/hsapiens.GRCh37.fasta
    networks:
      - webnet
      
  resserver:
    image: ega-data-api/ega-res
    depends_on: 
      - filedatabase
      - keyserver      
    ports:
      - "9092:9092"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss,LocalEGA
      - server.port=9092
      - ega.ebi.aws.access.key=D0MmGMmrOLwxjEE5
      - ega.ebi.aws.access.secret=PT6hqA1oaW65whte0y4NDMQ88KDCtBp9
      - ega.ebi.aws.endpoint.url=http://130.239.81.206:9000  
      - ega.ebi.aws.endpoint.region=europe
      - ega.sharedpass.path=/src/test/resources/pgp/ega.shared.pass      
      - FILEDATABASE.listOfServers=filedatabase:9051
      - RES2.listOfServers=resserver:9092
      - KEYSERVER.listOfServers=keyserver:9095 
      - EGA_EGA_CRAM_FASTA_A=""
      - EGA_EGA_CRAM_FASTA_B=""
      - EGA_EBI_FIRE_URL=""
      - EGA_EBI_FIRE_ARCHIVE=""
      - EGA_EBI_FIRE_KEY=""
      - service.archive.class=""
    networks:
      - webnet  
      
  filedatabase:
    image: ega-data-api/ega-filedatabase
    depends_on: 
      - postgres
    ports:
      - "9051:9051"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss
      - server.port=9051
      - DB_SCHEMA=dev_ega_file
      - DB_USERNAME=testuser
      - DB_PASSWORD=testpassw0rd      
      - DB_URL=jdbc:postgresql://postgres:5432/lega
    networks:
      - webnet        

  keyserver:
    image: ega-data-api/ega-keyserver
    depends_on: 
      - postgres
    ports:
      - "9095:9095"
    environment:
      - SPRING_PROFILES_ACTIVE=no-oss
      - server.port=9095        
      - ega.key.path=/src/test/resources/pgp/ega.sec
      - ega.keypass.path=/src/test/resources/pgp/ega.sec.pass
      - ega.sharedpass.path=/src/test/resources/pgp/ega.shared.pass
      - ega.publickey.url=/src/test/resources/pgp/ega.pub
      - ega.legacy.path=/src/test/resources/pgp/legacy.pass     
    networks:
      - webnet       
      
  postgres:
    image: anandmohan777/postgres:localegatest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpassw0rd
      - POSTGRES_DB=lega
      - PGDATA=/var/lib/postgresql/data/pgdata
    
    networks:
      - webnet

# Creating internal network from Docker Swarm.
networks:
  webnet:
